"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
import sys
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _load_dotenv(path):
    """Minimal .env reader: KEY=VALUE lines, '#' comments, optional quotes.
    Variables already set in the real environment win (setdefault), so Docker's
    env_file / environment and shell exports override the file."""
    try:
        lines = path.read_text(encoding='utf-8').splitlines()
    except FileNotFoundError:
        return
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, value = line.split('=', 1)
        os.environ.setdefault(key.strip(), value.strip().strip('"').strip("'"))


# Local development: put DEBUG=True in .env (see .env.example).
_load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-141-unw@7284(f^5la_k&+m@!tyz_$^z2+%^!m41c8dl_ur_i4',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Production-safe default: DEBUG is off unless the environment / .env turns it on.
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

# Always allowed: the production IP and local access. ALLOWED_HOSTS in the
# environment (comma-separated) adds more hosts, it never removes these.
ALLOWED_HOSTS = ['186.246.9.251', 'localhost', '127.0.0.1'] + [
    h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()
]


# Application definition

INSTALLED_APPS = [
    # daphne must be listed BEFORE django.contrib.staticfiles so its ASGI-aware
    # runserver replacement is what `python manage.py runserver` uses.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'corsheaders',
    'channels',
    'django_filters',
    # Apps
    'api',
]

MIDDLEWARE = [

    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # After sessions, before common: picks the language from the URL prefix
    # (/en/...) for i18n_patterns, otherwise falls back to LANGUAGE_CODE.
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR / 'backend' / 'templates',  # Django-rendered public pages (landing, ...)
            BASE_DIR / 'frontend' / 'dist',  # React build output (index.html)
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'
ASGI_APPLICATION = 'backend.asgi.application'

# Channel layers — InMemory is fine for local dev (single process).
# For production, switch to channels_redis with a Redis instance.
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Database
# DB_DIR env var lets Docker put the database in a mounted volume (/app/db/)
# so data survives container restarts. Locally it stays in the project root.
DB_DIR = Path(os.environ.get('DB_DIR', BASE_DIR))

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DB_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# Russian is the default and lives at / (prefix_default_language=False in
# backend/urls.py); English lives at /en/.
LANGUAGE_CODE = 'ru'

LANGUAGES = [
    ('ru', 'Русский'),
    ('en', 'English'),
]

LOCALE_PATHS = [
    BASE_DIR / 'backend' / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# CORS settings (allows frontend to connect)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5173",
]
# Allow null origin (file://)
CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^null$",
]

CORS_ALLOW_ALL_ORIGINS = True  # Should be there from before

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    # Per-user limits for views that set throttle_scope (ScopedRateThrottle).
    # Counters live in the default cache (no CACHES setting → per-process LocMemCache).
    'DEFAULT_THROTTLE_RATES': {
        'code_run': '30/min',  # /api/run-code/ and /api/run-tests/ together
    },
}

# Custom user model
AUTH_USER_MODEL = 'api.User'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JWT Settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR / 'backend' / 'static',  # public pages: /static/public/...
    BASE_DIR / 'frontend' / 'dist',  # React build output: /static/assets/...
]

# collectstatic writes content-hashed copies (landing.4f2c9a.css) plus a manifest,
# and {% static %} emits the hashed names when DEBUG is off, so new HTML can never
# be paired with an old stylesheet. WhiteNoise serves them (compressed, long cache)
# and keeps the unhashed originals too, which the React build's index.html
# references directly (/static/assets/index-<vite hash>.js).
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage'},
}

# The test runner renders templates without running collectstatic, where the
# manifest storage would fail on every {% static %}. Tests use plain storage; the
# test that checks hashed URLs overrides STORAGES and collects into a temp dir.
if len(sys.argv) > 1 and sys.argv[1] == 'test':
    STORAGES['staticfiles'] = {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'}

# Media files (author-uploaded lesson images)
# Served at /media/... — see backend/urls.py. In Docker, /app/media is a
# persistent volume so uploaded images survive container restarts.
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Allow embedding in iframes (needed for Step 11)
# SAMEORIGIN = only same-domain iframes; we use per-view exemption for cross-origin
X_FRAME_OPTIONS = 'SAMEORIGIN'