# Generated by Django 6.0.3 on 2026-05-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='attempts',
            field=models.IntegerField(default=0, help_text='How many times the student submitted this block (1 = solved first try)'),
        ),
    ]
