# Generated by Django 6.0.3 on 2026-06-04 20:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_progress_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer', models.JSONField(blank=True, help_text="The submitted answer payload (e.g. {'code': '...'} or {'selected': 2})", null=True)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.block')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'attempts',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['student', 'block', 'created_at'], name='attempts_student_f36177_idx')],
            },
        ),
    ]
