# Generated by Django 6.0.3 on 2026-06-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_attempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(choices=[('TEXT', 'Text Block'), ('QUIZ', 'Quiz Block'), ('CODE', 'Code Block'), ('FILL', 'Fill-in-the-blanks Block')], help_text='Block type (TEXT/QUIZ/CODE)', max_length=10),
        ),
    ]
